// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/service/locker/store.go

// Package locker is a generated GoMock package.
package locker

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// DeleteMutex mocks base method.
func (m *MockStore) DeleteMutex(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteMutex", key)
}

// DeleteMutex indicates an expected call of DeleteMutex.
func (mr *MockStoreMockRecorder) DeleteMutex(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMutex", reflect.TypeOf((*MockStore)(nil).DeleteMutex), key)
}

// GetMutex mocks base method.
func (m *MockStore) GetMutex(key string) (Mutex, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMutex", key)
	ret0, _ := ret[0].(Mutex)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetMutex indicates an expected call of GetMutex.
func (mr *MockStoreMockRecorder) GetMutex(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMutex", reflect.TypeOf((*MockStore)(nil).GetMutex), key)
}

// Lock mocks base method.
func (m *MockStore) Lock() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Lock")
}

// Lock indicates an expected call of Lock.
func (mr *MockStoreMockRecorder) Lock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockStore)(nil).Lock))
}

// NewMutex mocks base method.
func (m *MockStore) NewMutex(key string, unlockDelay time.Duration) Mutex {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMutex", key, unlockDelay)
	ret0, _ := ret[0].(Mutex)
	return ret0
}

// NewMutex indicates an expected call of NewMutex.
func (mr *MockStoreMockRecorder) NewMutex(key, unlockDelay interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMutex", reflect.TypeOf((*MockStore)(nil).NewMutex), key, unlockDelay)
}

// SetMutex mocks base method.
func (m *MockStore) SetMutex(key string, mutex Mutex, unlockDelay time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMutex", key, mutex, unlockDelay)
}

// SetMutex indicates an expected call of SetMutex.
func (mr *MockStoreMockRecorder) SetMutex(key, mutex, unlockDelay interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMutex", reflect.TypeOf((*MockStore)(nil).SetMutex), key, mutex, unlockDelay)
}

// Type mocks base method.
func (m *MockStore) Type() StoreType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(StoreType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockStoreMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockStore)(nil).Type))
}

// Unlock mocks base method.
func (m *MockStore) Unlock() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unlock")
}

// Unlock indicates an expected call of Unlock.
func (mr *MockStoreMockRecorder) Unlock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockStore)(nil).Unlock))
}

// MockMutex is a mock of Mutex interface.
type MockMutex struct {
	ctrl     *gomock.Controller
	recorder *MockMutexMockRecorder
}

// MockMutexMockRecorder is the mock recorder for MockMutex.
type MockMutexMockRecorder struct {
	mock *MockMutex
}

// NewMockMutex creates a new mock instance.
func NewMockMutex(ctrl *gomock.Controller) *MockMutex {
	mock := &MockMutex{ctrl: ctrl}
	mock.recorder = &MockMutexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutex) EXPECT() *MockMutexMockRecorder {
	return m.recorder
}

// Lock mocks base method.
func (m *MockMutex) Lock() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock")
	ret0, _ := ret[0].(error)
	return ret0
}

// Lock indicates an expected call of Lock.
func (mr *MockMutexMockRecorder) Lock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockMutex)(nil).Lock))
}

// Unlock mocks base method.
func (m *MockMutex) Unlock() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unlock indicates an expected call of Unlock.
func (mr *MockMutexMockRecorder) Unlock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockMutex)(nil).Unlock))
}
